### ISSUE TITLE
ListBox doesn't re-render when initially receiving props

### ISSUE THREAD

**Issue by jflayhart** [altayaydemir/react-dual-list-box#5]
I am using this with redux-form and all the other fields seem to render fine when the component state updates with new values (on initial load or full page refresh) except the dual-list-box component. Some plugins offer an "isPure" or "enableReinitialize" bool prop to check to re-render the component if state updates, but for whatever reason when I refresh the page, the list box shows no values, even though data is eventually available. If I leave the page and come back (without a full page refresh), then the list box shows data.

This is because an empty array is passed to the component, async request eventually fulfills and returns correct data, my form component re-renders, but list-box does not update with new data.

**Comment by jflayhart** [comment]
https://github.com/altayaydemir/react-dual-list-box/pull/6

**Comment by altayaydemir** [comment]
👍 😄
